#pragma once

typedef enum {
    DRIVER_ERR_OK = 0,
    DRIVER_ERR_INVALID_HANDLER,
    DRIVER_ERR_MALLOC_FAILED,
    DRIVER_ERR_INVALID_PARAM,
    DRIVER_ERR_READ_FAILED,
    DRIVER_ERR_WRITE_FAILED,
    DRIVER_ERR_COMM_FAILED,
    DRIVER_ERR_INVALID_COMMAND,
    DRIVER_ERR_UNKNOWN,
} driver_error_et;

